// scroll bar
import 'simplebar-react/dist/simplebar.min.css';
// import { Inter } from 'next/font/google';
import ThemeConfig from '@/theme';
import GlobalStyles from '@/theme/globalStyles';
// slick-carousel
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
// components
import Settings from '@/components/settings';
import ThemePrimaryColor from '@/components/ThemePrimaryColor';
// contexts
import { SettingsProvider } from '@/contexts/SettingsContext';
import MainLayout from '@/layouts/main';
import { Public_Sans } from 'next/font/google';

// Use the font you need
const public_Sans = Public_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'], // Specify weights as needed
});

export const metadata = {
  title: 'MD Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={public_Sans.className}>
        <SettingsProvider>
          <ThemeConfig>
            <ThemePrimaryColor>
              <GlobalStyles />
              <Settings />
              <MainLayout>{children}</MainLayout>
            </ThemePrimaryColor>
          </ThemeConfig>
        </SettingsProvider>
      </body>
    </html>
  );
}
